### ISSUE TITLE
投票：是否删除「不重复使用标点符号」的规则

### ISSUE THREAD

**Issue by shep-eth** [Next-DAO/chinese-copywriting-guidelines#2]
删除后将允许重复使用标点符号，虽然这么做会破坏句子的美观性，但有人认为在某些聊天场景中可以表达情绪。

删除后，下面的标点使用方式将被允许：
> 德国队竟然战胜了巴西队！！
> 
> 德国队竟然战胜了巴西队！！！！！！！！

注：投票结果仅供参考，最终由我来决定是否修改规则

**Comment by lucky2077** [comment]
美观很重要，不同意删除这条规则，如果不加限制，有些人喜欢 3 个叹号，有些人喜欢用 8 个，太乱了

**Comment by aurevae** [comment]
> 美观很重要，不同意删除这条规则，如果不加限制，有些人喜欢 3 个叹号，有些人喜欢用 8 个，太乱了

如果你的意图是强调或表达强烈的情感，重复使用标点符号是可以的。在非正式的文本或网络交流中，这样做能增强语气，使得阅读更富表现力。

**Comment by leonzijun** [comment]
视角感觉, 感叹号多, 有多激动. 虎扑都这样

**Comment by Betagg** [comment]
感叹号的数量确实可以区分情绪的等级强度。

**Comment by ShadowKingLKJ** [comment]
感叹号重复使用可以强调感情强烈。也可以区分对每件事重视程度

**Comment by MorisenTang** [comment]
已投！

**Comment by 0xAlanCui** [comment]
已投

**Comment by xiaok** [comment]
美观上的规则可以限制，文法上的创造不应禁止

**Comment by haha090777** [comment]
！！！！！！！！！！！！！！！！！！！！！！！！！！！我的最爱！！！！！！！！！！！！！！！！！！！！！！！

**Comment by 11001100111011101110001** [comment]
> 美观很重要，不同意删除这条规则，如果不加限制，有些人喜欢 3 个叹号，有些人喜欢用 8 个，太乱了

限制数量即可，例如 3 个感叹号足矣，多了确实影响美观。

**Comment by 0xPenny** [comment]
多标点对情绪有“泄洪”的作用，也是一种避免表情包刷屏的有效手段。表情包占地面积更大，对于有效信息的贡献更弱，建议“两害相较取其轻”。

**Comment by LemonStudio** [comment]
Done

**Comment by hlissnake** [comment]
同意删除，表达情绪可以增进家人的感情，比如！！！，还有无奈的 。。。。

**Comment by yilite81** [comment]
限制一天可使用一次

**Comment by Aroneth** [comment]
同意删除，表达情绪可以增进家人的感情，比如激动的 ！！！，还有无奈的 。。。。

**Comment by 0xPenny** [comment]
不赞同“允许重复使用，但又限制数量”的情况，审美本身很主观，“觉得五个感叹号好看”不比“觉得三个感叹号好看”劣等。

**Comment by haiyuzaifei** [comment]
家人间的情绪表达还是需要有的。私认为规则的建立是服务于家人

**Comment by 11001100111011101110001** [comment]
> 不赞同“允许重复使用，但又限制数量”的情况，审美本身很主观，“觉得五个感叹号好看”不比“觉得三个感叹号好看”劣等。

更多的是情绪控制问题，限制数量既可以满足家人情绪的表达，又可以风格统一。

**Comment by AndyJiangPro** [comment]
Done

**Comment by dylanlyu123** [comment]
同意以上关于情绪表达部分的论述

**Comment by highfar888** [comment]
已投

**Comment by 0xPenny** [comment]
> > 不赞同“允许重复使用，但又限制数量”的情况，审美本身很主观，“觉得五个感叹号好看”不比“觉得三个感叹号好看”劣等。
> 
> 更多的是情绪控制问题，限制数量既可以满足家人情绪的表达，又可以风格统一。

限制了还怎么表达情绪？要统一就统一，要放开就放开。不能把我的情绪，限制在你的舒适区里。

**Comment by 11001100111011101110001** [comment]
> > > 不赞同“允许重复使用，但又限制数量”的情况，审美本身很主观，“觉得五个感叹号好看”不比“觉得三个感叹号好看”劣等。
> > 
> > 
> > 更多的是情绪控制问题，限制数量既可以满足家人情绪的表达，又可以风格统一。
> 
> 限制了还怎么表达情绪？要统一就统一，要放开就放开。不能把我的情绪，限制在你的舒适区里。

并不是限制在我的舒适区，情绪的适当表达和控制都是必须的。

**Comment by simbafrom2077** [comment]
支持！！！

**Comment by Yanyu09** [comment]
同意可以重复使用标点符号，这样可以让冷漠的文字有了温度！！！！！

**Comment by dolice218** [comment]
我自己很少用，但支持不限制别人使用

**Comment by qwer277** [comment]
我们是人，不是机器人，不能为了美观和标准失去情绪的表达！！！！！！！！！！

**Comment by destinyyg** [comment]
不能失去情绪表达

**Comment by shintemy** [comment]
Done!!!

**Comment by neopaoe** [comment]
表达强烈意图，支持保留

**Comment by pixiu12345** [comment]
支持

**Comment by holyJiang** [comment]
> 删除后将允许重复使用标点符号，虽然这么做会破坏句子的美观性，但有人认为在某些聊天场景中可以表达情绪。
> 
> 删除后，下面的标点使用方式将被允许：
> 
> > 德国队竟然战胜了巴西队！！
> > 德国队竟然战胜了巴西队！！！！！！！！
> 
> 注：投票结果仅供参考，最终由我来决定是否修改规则



> 删除后将允许重复使用标点符号，虽然这么做会破坏句子的美观性，但有人认为在某些聊天场景中可以表达情绪。
> 
> 删除后，下面的标点使用方式将被允许：
> 
> > 德国队竟然战胜了巴西队！！
> > 德国队竟然战胜了巴西队！！！！！！！！
> 
> 注：投票结果仅供参考，最终由我来决定是否修改规则

我想要好多叹号！！！

**Comment by MorisenTang** [comment]
同意删除这条规则。文字是冰冷的，有很多人需要重复使用标点符号来表达自己不同程度的情绪。

**Comment by winterwd1201** [comment]
投不删除一票，做投资不需要太多情绪的表达，或者 3 个足矣。

**Comment by PingMaoer** [comment]
赞成！偶尔的重复是为了表达丰富的情感。

**Comment by lidonghao1116** [comment]
支持。

**Comment by charlesx1028** [comment]
赞成，重复的标点符号加大了情感的表现力，让群感觉更live更有趣

**Comment by softlipa1018** [comment]
赞成删除 ^ ^

**Comment by Jarvis0811** [comment]
赞成！

**Comment by EricHomberg** [comment]
Done

**Comment by yandong-ac** [comment]
赞成删除

**Comment by cmy0816** [comment]
保持统一较好，反对重复使用。

**Comment by salmon332** [comment]
爱所有同意删除的人！！

**Comment by EricXUzi** [comment]
反对

**Comment by Yanelis66** [comment]
反对重复使用，太烦了

**Comment by yono-liu** [comment]
赞成

**Comment by shep-eth** [comment]
https://github.com/Next-DAO/chinese-copywriting-guidelines/pull/4

**Comment by wangte168** [comment]
支持！
