### ISSUE TITLE
投票：是否删除「专有名词使用正确的大小写」的规则

### ISSUE THREAD

**Issue by shep-eth** [Next-DAO/chinese-copywriting-guidelines#3]
删除后，下面的使用方式将被允许：

> 你注册 Github 了吗？
> 
> 你注册 github 了吗？
>
> 你的 microsoft 账号是多少？
>
> 我是 ios 开发者。

注：投票结果仅供参考，最终由我来决定是否修改规则

**Comment by EricHomberg** [comment]
个人觉得这种可以接受

**Comment by Aroneth** [comment]
支持删除，这样更方便，大小写 绝大部分情况下不会引起歧义

**Comment by krito1234** [comment]
Done

**Comment by 0xPenny** [comment]
有些专有名词太奇怪了，比如 helloNFT 这种，开头不是大写，结尾不是小写，也不知道谁想出来的，这不是坑人吗？

**Comment by lucky2077** [comment]
支持删除，强如 Apple，自带输入法里也只能自动纠正部分专有名词，能做到的是，知道的专有名词，尽可能写对

**Comment by Eas0nGu0** [comment]
我都可以，但还是更喜欢随意一点

**Comment by 17y** [comment]
前些年简历写 ios 的都被我筛掉了，但还是投了 yes😂

**Comment by 0xAlanCui** [comment]
已投

**Comment by leonzijun** [comment]
同意删除打的时候不会习惯大小写 .

**Comment by haha090777** [comment]
我是enfp，我喜欢随心所欲

**Comment by dylanlyu123** [comment]
同意，但是日常尽可能的做到规范

**Comment by haha090777** [comment]
我听shep的

**Comment by shep-eth** [comment]
> 我听shep的

没加盘古之白

**Comment by highfar888** [comment]
支持删除

**Comment by dolice218** [comment]
支持删除

**Comment by william2118** [comment]
反对删除，想想专有名词为什么被称为专有名词？

**Comment by qwer277** [comment]
支持删除，因为专有名词如何界定就是一门新的功课了。循序渐进的方式可能更利于改变。

**Comment by destinyyg** [comment]
保持格式才是残酷

**Comment by shintemy** [comment]
我个人还是会尽量使用专有名词的正式大小写，但不强求

**Comment by neopaoe** [comment]
尽量保留专有名词专属大小写

**Comment by pixiu12345** [comment]
支持删除

**Comment by MorisenTang** [comment]
同意删除这条规则。个人感觉可以在某种程度上提高大家的打字效率？

**Comment by zjfrey** [comment]
删了好一些，不然学习成本太高了…

**Comment by jassaj678** [comment]
可以接受删除，但知道的专有名词会做到规范

**Comment by winterwd1201** [comment]
反对删除，这样更能强制要求保持好习惯。

**Comment by Sea0x** [comment]
知名品牌的大小写要坚持，比如 Apple, Google。

小品牌（比如 helloNFT）的大小写不要强求，因为小品牌的这个大小写本身就有点奇怪。

**Comment by PingMaoer** [comment]
我是悟空，从练习盘古之白开始。

**Comment by lidonghao1116** [comment]
同意，知名专有名词输入法也会有纠正。

**Comment by cmy0816** [comment]
支持删除。

**Comment by louisfy** [comment]
支持删除，主要是因为名词并不是真的统一一个规则规范

**Comment by zk-cellprotocol** [comment]
专有名词是一种尊重，留着，支持校长的意见。

**Comment by Yanyu09** [comment]
投票完成。

**Comment by softlipa1018** [comment]
个人支持删除，但如果是科普类、大品牌的可以在不犯规的前提下互相友好纠正，大家可以在日后逐步打出正确的大小写。

**Comment by Yanelis66** [comment]
个人支持删除

**Comment by Jarvis0811** [comment]
各有利弊，支持！

**Comment by shileitencent** [comment]
done

**Comment by salmon332** [comment]
投咯

**Comment by yandong-ac** [comment]
支持删除！专有名词口语化，减少沟通成本

**Comment by sevenhaha7777** [comment]
支持！

**Comment by EricXUzi** [comment]
同意 👌

**Comment by Betagg** [comment]
如果是商务工作场景下，这个格式确实比较有必要

**Comment by yono-liu** [comment]
同意✅

**Comment by shep-eth** [comment]
https://github.com/Next-DAO/chinese-copywriting-guidelines/pull/4

**Comment by wangte168** [comment]
投了
